version: "3.8"

services:
  db:
    image: postgis/postgis:17-3.5
    container_name: postgis_db
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  webapp:
    build:
      context: .
      dockerfile: dockerfile
    container_name: vayven-webapp
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend
      - frontend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: iturbelothar9@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ${PGPASSWORD}
    depends_on:
      - db
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
  frontend:


